#ifndef __ADAPTORTYPES_H__
#define __ADAPTORTYPES_H__

typedef struct StatementHandleStruct StatementHandle;

typedef struct AnalysisAdaptorStruct AnalysisAdaptor;
typedef struct AssemblyMapperAdaptorStruct AssemblyMapperAdaptor;
typedef struct BaseAdaptorStruct BaseAdaptor;
typedef struct BaseDBAdaptorStruct BaseDBAdaptor;
typedef struct BaseFeatureAdaptorStruct BaseFeatureAdaptor;
typedef struct CoordSystemAdaptorStruct CoordSystemAdaptor;
typedef struct ChromosomeAdaptorStruct ChromosomeAdaptor;
typedef struct CloneAdaptorStruct CloneAdaptor;
typedef struct DBAdaptorStruct DBAdaptor;
typedef struct DBConnectionStruct DBConnection;
typedef struct DBEntryAdaptorStruct DBEntryAdaptor;
typedef struct DNAAlignFeatureAdaptorStruct DNAAlignFeatureAdaptor;
typedef struct ExonAdaptorStruct ExonAdaptor;
typedef struct GeneAdaptorStruct GeneAdaptor;
typedef struct MetaContainerStruct MetaContainer;
typedef struct PredictionTranscriptAdaptorStruct PredictionTranscriptAdaptor;
typedef struct ProteinAlignFeatureAdaptorStruct ProteinAlignFeatureAdaptor;
typedef struct RawContigAdaptorStruct RawContigAdaptor;
typedef struct RepeatConsensusAdaptorStruct RepeatConsensusAdaptor;
typedef struct RepeatFeatureAdaptorStruct RepeatFeatureAdaptor;
typedef struct SequenceAdaptorStruct SequenceAdaptor;
typedef struct SimpleFeatureAdaptorStruct SimpleFeatureAdaptor;
typedef struct SupportingFeatureAdaptorStruct SupportingFeatureAdaptor;
typedef struct SliceAdaptorStruct SliceAdaptor;
typedef struct TranscriptAdaptorStruct TranscriptAdaptor;
typedef struct TranslationAdaptorStruct TranslationAdaptor;

#endif
