#ifndef __COMPARAADPTORTPES_H__
#define __COMPARAADPTORTPES_H__

typedef struct BaseComparaAdaptorStruct BaseComparaAdaptor;
typedef struct ComparaDBAdaptorStruct ComparaDBAdaptor;
typedef struct ComparaDNAAlignFeatureAdaptorStruct ComparaDNAAlignFeatureAdaptor;
typedef struct DNAFragAdaptorStruct DNAFragAdaptor;
typedef struct GenomicAlignAdaptorStruct GenomicAlignAdaptor;
typedef struct GenomeDBAdaptorStruct GenomeDBAdaptor;
typedef struct HomologyAdaptorStruct HomologyAdaptor;
typedef struct SyntenyAdaptorStruct SyntenyAdaptor;
typedef struct SyntenyRegionAdaptorStruct SyntenyRegionAdaptor;

#endif
